# themes
import:
  - ~/.config/alacritty/themes/themes/github_light.yaml

# Font configuration
font:
  size: 12
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  normal:
    family: Caskaydia Cove Nerd Font
    style: Medium
  bold:
    family: Caskaydia Cove Nerd Font
  italic:
    family: Caskaydia Cove Nerd Font
